services:
  colab:
    image: asia-docker.pkg.dev/colab-images/public/runtime

    restart: unless-stopped

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

    build:
      context: .
      shm_size: '1gb'
    shm_size: '1gb'

    ports:
      - "0.0.0.0:9000:8080"
      - "0.0.0.0:7860:7860"

    environment:
      - JUPYTER_TOKEN=2238522
    command: >
      bash -c "
        sed -i 's/\"serverHost\": \"\"/\"serverHost\": \"0.0.0.0\"/' /datalab/web/config/settings.json &&
        exec /datalab/run.sh
      "

    volumes:
      - ./content:/content
      - ./cache:/root/.cache
