#!/bin/bash

# Check if user is in docker group
if ! groups | grep -q docker; then
    echo "Error: User is not in docker group."
    echo "Please run: sudo usermod -aG docker $USER"
    echo "Then logout and login again, or run: newgrp docker"
    exit 1
fi

# Check if NVIDIA GPU is available (REQUIRED)
if ! command -v nvidia-smi &> /dev/null || ! nvidia-smi &> /dev/null; then
    echo "Error: NVIDIA GPU is required but not detected!"
    echo "This Colab environment requires GPU support."
    exit 1
fi

echo "NVIDIA GPU detected"

# Check if nvidia-container-toolkit is installed (REQUIRED)
if ! dpkg -l | grep -q nvidia-container-toolkit && ! dpkg -l | grep -q nvidia-docker2; then
    echo "Error: nvidia-container-toolkit is required but not installed!"
    echo ""
    echo "Please run the following command to install it:"
    echo "  ./install_gpu_support.sh"
    echo ""
    exit 1
fi

echo "nvidia-container-toolkit found - enabling GPU support..."

# Create docker-compose.override.yml with GPU configuration
cat > docker-compose.override.yml << 'EOF'
# GPU configuration (automatically generated by run.sh)
services:
  colab:
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
EOF

echo "Starting Google Colab container with GPU support..."
# Support both Docker Compose V2 ("docker compose") and V1 ("docker-compose").
if docker compose version &> /dev/null; then
    compose_cmd="docker compose"
elif command -v docker-compose &> /dev/null; then
    compose_cmd="docker-compose"
else
    echo "Error: Docker Compose is not available (tried 'docker compose' and 'docker-compose')."
    exit 1
fi

# Some environments require sudo even when the user is in the docker group.
if ! docker info &> /dev/null; then
    if sudo docker info &> /dev/null; then
        echo "Docker requires sudo in this environment; retrying with sudo."
        compose_cmd="sudo $compose_cmd"
    else
        echo "Error: Cannot access the Docker daemon. Is it running?"
        echo "Try: sudo $compose_cmd up -d"
        exit 1
    fi
fi

$compose_cmd up -d
